# version: "3.9"

################################################################################

services:
  genesis:
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
