# version: "3.9"

################################################################################

services:
  genesis:
    hostname: genesis
    privileged: true
    environment:
      # Pass current user and group IDs.
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
      # Display X Server GUIs.
      - DISPLAY=${DISPLAY:-:1}
      - QT_X11_NO_MITSHM=1
      # Configure the PulseAudio interface.
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
      - TERM=xterm-256color
    image: genesis
    # build:
    #   context: ../
    #   dockerfile: ./docker/ur5e-devel/Dockerfile
    #   args:
    #     - DOCKERFILE_COMMIT_SHORT_SHA
    volumes:
      # Map repository root for convenient access.
      - ../:/root/Genesis/
      # Grant display access to X Server.
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
      # Grant audio access to PulseAudio.
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - ../:/root/Genesis
    devices:
      - /dev/:/dev/
    working_dir: /root/Genesis
    network_mode: host
    ipc: host
    pid: host
    # # ports:
    # #   - 9090:9090 # Expose 'rosbridge_suite' default port: https://github.com/RobotWebTools/rosbridge_suite
    # #   - 10000:10000 # Expose 'ros_tcp_endpoint' default port: https://github.com/Unity-Technologies/ROS-TCP-Endpoint
    command: /root/Genesis/docker/initialize-docker-container.bash
